#ifndef DEFINES_HPP_
#define DEFINES_HPP_

#include <string>

std::string CommandType
{
	COMMAND_TYPE_GO,
	COMMAND_TYPE_INSERT,
	COMMAND_TYPE_BACK,
	COMMAND_TYPE_FORWARD,
	COMMAND_TYPE_REMOVE,
	COMMAND_TYPE_PRINT,
	COMMAND_TYPE_SORT_URL,
	COMMAND_TYPE_TIME,
	COMMAND_TYPE_SEARCH
	COMMAND_TYPE_SHOW_MENU
}

#ifndef